#!/usr/bin/env python3

import re
from sys import argv
import os

sanitize_latex = {
    r"\\": r"\textbackslash",
    r'{': r'\{',
    r'}': r'\}',
    r'_': r'\_',
    r'$': r'\$',
    r'#': r'\#',
    r'&': r'\&',
}

latex_addspace = {
    r'√': r'\sqrt',
    r'≤': r'\leq',
    r'≥': r'\geq',
    r'≫': r'\gg',
    r'≪': r'\ll',
    r'∈': r'\in',
    r'. . .': r'\ldots',
    '...': r'\ldots',
    r'∞': r'\infty',
    r'°': r'\degree',
    r' ln ': r' \ln ',
    r' lim ': r' \lim ',
    r'≡': r'\equiv',
    r'→': r'\to',
    r'⇒': r'\implies',
    r'±': r'\pm',
    r'×': r'\times',
    r'¬': r'\neg',
    r'~': r'\sim',
    r'≠': r'\neq',
    r'≈': r'\approx',
    r'∂': r'\partial',
    r'': r'\gg',
#    r'': r'\succ',
    r'⊂': r'\subset',
    r' ∗': r'^*',
    r':=': r'\coloneq',
    r'∩': r'\bigcap',
    r'·': r'\cdot',
    r'•': r'\bullet',
    r'∀': r'\forall',
}


whitespace = {
    # This will be parsed literally, not as regex.
    '\t': ' ',  # tab
    '\v': ' ',  # vertical tab
    '\f': ' ',  # form feed
    '\r': '\n', # carriage return (replace with new line)
    u'\u0085': '\n', # next line
    u'\u00A0': ' ',  # no-break space 
    u'\u1680': ' ',  # ogham space mark
    u'\u2000': ' ',  # en quad
    u'\u2001': ' ',  # em quad
    u'\u2002': ' ',  # en space 
    u'\u2003': ' ',  # em space
    u'\u2004': ' ',  # three-per-em space
    u'\u2005': ' ',  # four-per-em space
    u'\u2006': ' ',  # six-per-em space
    u'\u2007': ' ',  # figure space
    u'\u2008': ' ',  # punctuation space
    u'\u2009': ' ',  # thin space
    u'\u200A': ' ',  # hair space
    u'\u2028': '\n',  # line separator
    u'\u2029': '\n\n',  # paragraph separator
    u'\u202F': ' ',  # narrow no-break space
    u'\u205F': ' ',  # medium mathematical space
    u'\u3000': ' ',  # ideographic space
}

greek = {
    r'α': r'\alpha',
    r'β': r'\beta',
    r'γ': r'\gamma',
    r'Γ': r'\Gamma',
    r'δ': r'\delta',
    r'Δ': r'\Delta',
    r'ε': r'\epsilon',
    r'ζ': r'\zeta',
    r'η': r'\eta',
    r'θ': r'\theta',
    r'Θ': r'\Theta',
    r'ι': r'\iota',
    r'κ': r'\kappa',
    r'λ': r'\lambda',
    r'Λ': r'\Lambda',
    r'μ': r'\mu',
    r'ν': r'\nu',
    r'ξ': r'\xi',
    r'Ξ': r'\Xi',
    r'ο': r'\omnicron',
    r'π': r'\pi',
    r'Π': r'\Pi',
    r'ρ': r'\rho',
    r'σ': r'\sigma',
    r'ς': r'\varsigma',
    r'Σ': r'\Sigma',
    r'τ': r'\tau',
    r'υ': r'\upsilon',
    r'φ': r'\phi',
    r'Φ': r'\Phi',
    r'χ': r'\chi',
    r'ψ': r'\psi',
    r'Ψ': r'\Psi',
    r'ω': r'\omega',
    r'Ω': r'\Omega',
    r'א': r'\aleph',
    r'ב': r'\beth',
    r'ג': r'\gimel',
    r'ד': r'\daleth'
}

exact_replacements = {
    'i.e. ': r'i.e.\ ',
    'ie. ': r'ie.\ ',
    'vs. ': r'vs.\ ',
    'Ch. ': r'Ch.\ ',
    'Ex. ': r'Ex.\ ',
    'e.g. ': r'e.g.\ ',
    'eg. ': r'eg.\ ',
    r'–': '--', # en dash
    r'—': r'---', # em dash
    r'−': r'-', # minus
    r'∗': r'*',
    r'': '',  # etx, or end of text
    r'': '',  # stx, or start of text
    r'': '',  # nak, or negative acknowledge
    r'': '',  # soh, or start of heading
    r'': '',  # dc4, or device control four
    r'\mũ': r'\tilde{\mu}',  # because greek letters get replaced first.
    r'': "'",  # prime (math mode `'`), I think
    'cos(': r'\cos(',
    'sin(': r'\sin(',
    'tan(': r'\tan(',
    'arcsin(': r'\arcsin(',
    'arccos(': r'\arccos(',
    'arctan(': r'\arctan(',
}






def make_smallcaps(regex_match):
    text = regex_match.groups(1)[0]
    return r'\textsc{' + text.lower() + r'}'

def itemize(regex_match):
    text = regex_match.groups(1)[0]
    #print("Replacing: `{}` with `{}`".format(text, "\\item % {} \n".format(text)))
    return "\\item % {} \n".format(text)

regex_replacements = {
    # both the key and value will be interpreted as regex.
    # the value could also be a function.
    r'[\t\f' + u'\u00A0' + ']': ' ',  # replace weird spaces (tabs, form-feeds and non-breaking spaces) with a regular space.
    r'([A-Z]{3,})': make_smallcaps,
    # Various itemize/enumerates
    r'^\s*\(([a-z])\s?\)': itemize,
    r'^([a-z])\.\s': itemize,
    r'^\s*•': r'\item',
    r'^([0-9])\.\s': itemize
}




def merge_dicts(*dict_args):
    '''
    Given any number of dicts, shallow copy and merge into a new dict,
    precedence goes to key value pairs in latter dicts.
    '''
    result = {}
    for dictionary in dict_args:
        result.update(dictionary)
    return result


def replace_regex(line, replacements):
    for old_regex, new_regex in replacements.items():
        line = re.sub(old_regex, new_regex, line)
    return line


def replace_fixed_str(line, replacements):
    for old, new in replacements.items():
        if old in line:
            line = line.replace(old, new)
    return line


def replace_add_space(line, replacements):
    '''Make replacements, adding a space after if there isn't one already.'''
    for old, new in replacements.items():
        if old in line:
            plus_space = old + ' '
            if plus_space in line:
                line = line.replace(old, new)
            else:
                line = line.replace(old, new + ' ')
    return line


def replace_lines():
    updated_lines = []
    for line in get_text():
        line = line.strip()
        line = replace_fixed_str(line, whitespace)
        line = replace_fixed_str(line, sanitize_latex)
        line = replace_fixed_str(line, accented)
        line = replace_regex(line, regex_replacements)
        line = replace_add_space(line, greek)
        line = replace_add_space(line, latex_addspace)
        line = replace_fixed_str(line, exact_replacements)
        updated_lines.append(line)
    return updated_lines


def get_text():
    if len(argv) > 1 and os.path.isfile(argv[1]):
        with open(argv[1], 'rt') as f:
            lines = f.readlines()
    else:
        try:
           import pyperclip
        except ImportError:
            print("Please install the `pyperclip` package, or provide arguments on the command line")
            exit(1)
        lines = pyperclip.paste().replace('\r', '\n').split('\n')
        #print("Sorry, pyperclip is segfaulting...")
        #print("Try again, providing a file on the command line.")
        #exit()
    return lines

def write_text():
    lines = replace_lines()
    if len(argv) > 2:
        with open(argv[2], 'wt') as outfile:
            for line in lines:
                outfile.write(line + '\n')
    else:
        for line in lines:
            print(line)



accented = {
    "á": r"\acute{a}",
    "ā": r"\bar{a}",
    "ă": r"\breve{a}",
    "ǎ": r"\check{a}",
    "ä": r"\ddot{a}",
    "ȧ": r"\dot{a}",
    "à": r"\grave{a}",
    "â": r"\hat{a}",
    "ã": r"\tilde{a}",
    "b́": r"\acute{b}",
    "b̄": r"\bar{b}",
    "b̆": r"\breve{b}",
    "b̌": r"\check{b}",
    "b̈": r"\ddot{b}",
    "ḃ": r"\dot{b}",
    "b̀": r"\grave{b}",
    "b̂": r"\hat{b}",
    "b̃": r"\tilde{b}",
    "ć": r"\acute{c}",
    "c̄": r"\bar{c}",
    "c̆": r"\breve{c}",
    "č": r"\check{c}",
    "c̈": r"\ddot{c}",
    "ċ": r"\dot{c}",
    "c̀": r"\grave{c}",
    "ĉ": r"\hat{c}",
    "c̃": r"\tilde{c}",
    "d́": r"\acute{d}",
    "d̄": r"\bar{d}",
    "d̆": r"\breve{d}",
    "ď": r"\check{d}",
    "d̈": r"\ddot{d}",
    "ḋ": r"\dot{d}",
    "d̀": r"\grave{d}",
    "d̂": r"\hat{d}",
    "d̃": r"\tilde{d}",
    "é": r"\acute{e}",
    "ē": r"\bar{e}",
    "ĕ": r"\breve{e}",
    "ě": r"\check{e}",
    "ë": r"\ddot{e}",
    "ė": r"\dot{e}",
    "è": r"\grave{e}",
    "ê": r"\hat{e}",
    "ẽ": r"\tilde{e}",
    # f didn't come through well in the pasting
    "ǵ": r"\acute{g}",
    "ḡ": r"\bar{g}",
    "ğ": r"\breve{g}",
    "ǧ": r"\check{g}",
    "g̈": r"\ddot{g}",
    "ġ": r"\dot{g}",
    "g̀": r"\grave{g}",
    "ĝ": r"\hat{g}",
    "g̃": r"\tilde{g}",
    "h́": r"\acute{h}",
    "h̄": r"\bar{h}",
    "h̆": r"\breve{h}",
    "ȟ": r"\check{h}",
    "ḧ": r"\ddot{h}",
    "ḣ": r"\dot{h}", 
    "h̀": r"\grave{h}",
    "ĥ": r"\hat{h}",
    "h̃": r"\tilde{h}",
    "í": r"\acute{i}",
    "ī": r"\bar{i}",
    "ĭ": r"\breve{i}",
    "ǐ": r"\check{i}",
    "ï": r"\ddot{i}",
    "i̇": r"\dot{i}",
    "ì": r"\grave{i}",
    "î": r"\hat{i}",
    "ĩ": r"\tilde{i}",
    "j́": r"\acute{j}",
    "j̄": r"\bar{j}",
    "j̆": r"\breve{j}",
    "ǰ": r"\check{j}",
    "j̈": r"\ddot{j}",
    "j̇": r"\dot{j}",
    "j̀": r"\grave{j}",
    "ĵ": r"\hat{j}",
    "j̃": r"\tilde{j}",
    "ḱ": r"\acute{k}",
    "k̄": r"\bar{k}",
    "k̆": r"\breve{k}",
    "ǩ": r"\check{k}",
    "k̈": r"\ddot{k}",
    "k̇": r"\dot{k}",
    "k̀": r"\grave{k}",
    "k̂": r"\hat{k}",
    "k̃": r"\tilde{k}",
    # l didn't come through well.
    "ḿ": r"\acute{m}",
    "m̄": r"\bar{m}",
    "m̆": r"\breve{m}",
    "m̌": r"\check{m}",
    "m̈": r"\ddot{m}",
    "ṁ": r"\dot{m}",
    "m̀": r"\grave{m}",
    "m̂": r"\hat{m}",
    "m̃": r"\tilde{m}",
    "ń": r"\acute{n}",
    "n̄": r"\bar{n}",
    "n̆": r"\breve{n}",
    "ň": r"\check{n}",
    "n̈": r"\ddot{n}",
    "ṅ": r"\dot{n}",
    "ǹ": r"\grave{n}",
    "n̂": r"\hat{n}",
    "ñ": r"\tilde{n}",
    "ó": r"\acute{o}",
    "ō": r"\bar{o}",
    "ŏ": r"\breve{o}",
    "ǒ": r"\check{o}",
    "ö": r"\ddot{o}",
    "ȯ": r"\dot{o}",
    "ò": r"\grave{o}",
    "ô": r"\hat{o}",
    "õ": r"\tilde{o}",
    "ṕ": r"\acute{p}",
    "p̄": r"\bar{p}",
    "p̆": r"\breve{p}",
    "p̌": r"\check{p}",
    "p̈": r"\ddot{p}",
    "ṗ": r"\dot{p}",
    "p̀": r"\grave{p}",
    "p̂": r"\hat{p}",
    "p̃": r"\tilde{p}",
    "q́": r"\acute{q}",
    "q̄": r"\bar{q}",
    "q̆": r"\breve{q}",
    "q̌": r"\check{q}",
    "q̈": r"\ddot{q}",
    "q̇": r"\dot{q}",
    "q̀": r"\grave{q}",
    "q̂": r"\hat{q}",
    "q̃": r"\tilde{q}",
    "ŕ": r"\acute{r}",
    "r̄": r"\bar{r}",
    "r̆": r"\breve{r}",
    "ř": r"\check{r}",
    "r̈": r"\ddot{r}",
    "ṙ": r"\dot{r}",
    "r̀": r"\grave{r}",
    "r̂": r"\hat{r}",
    "r̃": r"\tilde{r}",
    "ś": r"\acute{s}",
    "s̄": r"\bar{s}",
    "s̆": r"\breve{s}",
    "š": r"\check{s}",
    "s̈": r"\ddot{s}",
    "ṡ": r"\dot{s}",
    "s̀": r"\grave{s}",
    "ŝ": r"\hat{s}",
    "s̃": r"\tilde{s}",
    "t́": r"\acute{t}",
    "t̄": r"\bar{t}",
    "t̆": r"\breve{t}",
    "ť": r"\check{t}",
    "ẗ": r"\ddot{t}",
    "ṫ": r"\dot{t}",
    "t̀": r"\grave{t}",
    "t̂": r"\hat{t}",
    "t̃": r"\tilde{t}",
    "ú": r"\acute{u}",
    "ū": r"\bar{u}",
    "ŭ": r"\breve{u}",
    "ǔ": r"\check{u}",
    "ü": r"\ddot{u}",
    "u̇": r"\dot{u}",
    "ù": r"\grave{u}",
    "û": r"\hat{u}",
    "ũ": r"\tilde{u}",
    "v́": r"\acute{v}",
    "v̄": r"\bar{v}",
    "v̆": r"\breve{v}",
    "v̌": r"\check{v}",
    "v̈": r"\ddot{v}",
    "v̇": r"\dot{v}",
    "v̀": r"\grave{v}",
    "v̂": r"\hat{v}",
    "ṽ": r"\tilde{v}",
    "ẃ": r"\acute{w}",
    "w̄": r"\bar{w}",
    "w̆": r"\breve{w}",
    "w̌": r"\check{w}",
    "ẅ": r"\ddot{w}",
    "ẇ": r"\dot{w}",
    "ẁ": r"\grave{w}",
    "ŵ": r"\hat{w}",
    "w̃": r"\tilde{w}",
    "x́": r"\acute{x}",
    "x̄": r"\bar{x}",
    "x̆": r"\breve{x}",
    "x̌": r"\check{x}",
    "ẍ": r"\ddot{x}",
    "ẋ": r"\dot{x}",
    "x̀": r"\grave{x}",
    "x̂": r"\hat{x}",
    "x̃": r"\tilde{x}",
    "ý": r"\acute{y}",
    "ȳ": r"\bar{y}",
    "y̆": r"\breve{y}",
    "y̌": r"\check{y}",
    "ÿ": r"\ddot{y}",
    "ẏ": r"\dot{y}",
    "ỳ": r"\grave{y}",
    "ŷ": r"\hat{y}",
    "ỹ": r"\tilde{y}",
    "ź": r"\acute{z}",
    "z̄": r"\bar{z}",
    "z̆": r"\breve{z}",
    "ž": r"\check{z}",
    "z̈": r"\ddot{z}",
    "ż": r"\dot{z}",
    "z̀": r"\grave{z}",
    "ẑ": r"\hat{z}",
    "z̃": r"\tilde{z}",
    "Á": r"\acute{A}",
    "Ā": r"\bar{A}",
    "Ă": r"\breve{A}",
    "Ǎ": r"\check{A}",
    "Ä": r"\ddot{A}",
    "Ȧ": r"\dot{A}",
    "À": r"\grave{A}",
    "Â": r"\hat{A}",
    "Ã": r"\tilde{A}",
    "B́": r"\acute{B}",
    "B̄": r"\bar{B}",
    "B̆": r"\breve{B}",
    "B̌": r"\check{B}",
    "B̈": r"\ddot{B}",
    "Ḃ": r"\dot{B}",
    "B̀": r"\grave{B}",
    "B̂": r"\hat{B}",
    "B̃": r"\tilde{B}",
    "Ć": r"\acute{C}",
    "C̄": r"\bar{C}",
    "C̆": r"\breve{C}",
    "Č": r"\check{C}",
    "C̈": r"\ddot{C}",
    "Ċ": r"\dot{C}",
    "C̀": r"\grave{C}",
    "Ĉ": r"\hat{C}",
    "C̃": r"\tilde{C}",
    "D́": r"\acute{D}",
    "D̄": r"\bar{D}",
    "D̆": r"\breve{D}",
    "Ď": r"\check{D}",
    "D̈": r"\ddot{D}",
    "Ḋ": r"\dot{D}",
    "D̀": r"\grave{D}",
    "D̂": r"\hat{D}",
    "D̃": r"\tilde{D}",
    "É": r"\acute{E}",
    "Ē": r"\bar{E}",
    "Ĕ": r"\breve{E}",
    "Ě": r"\check{E}",
    "Ë": r"\ddot{E}",
    "Ė": r"\dot{E}",
    "È": r"\grave{E}",
    "Ê": r"\hat{E}",
    "Ẽ": r"\tilde{E}",
    "F́": r"\acute{F}",
    "F̄": r"\bar{F}",
    "F̆": r"\breve{F}",
    "F̌": r"\check{F}",
    "F̈": r"\ddot{F}",
    "Ḟ": r"\dot{F}",
    "F̀": r"\grave{F}",
    "F̂": r"\hat{F}",
    "F̃": r"\tilde{F}",
    "Ǵ": r"\acute{G}",
    "Ḡ": r"\bar{G}",
    "Ğ": r"\breve{G}",
    "Ǧ": r"\check{G}",
    "G̈": r"\ddot{G}",
    "Ġ": r"\dot{G}",
    "G̀": r"\grave{G}",
    "Ĝ": r"\hat{G}",
    "G̃": r"\tilde{G}",
    "H́": r"\acute{H}",
    "H̄": r"\bar{H}",
    "H̆": r"\breve{H}",
    "Ȟ": r"\check{H}",
    "Ḧ": r"\ddot{H}",
    "Ḣ": r"\dot{H}",
    "H̀": r"\grave{H}",
    "Ĥ": r"\hat{H}",
    "H̃": r"\tilde{H}",
    "Ī": r"\bar{I}",
    "Ĭ": r"\breve{I}",
    "Ǐ": r"\check{I}",
    "Ï": r"\ddot{I}",
    "İ": r"\dot{I}",
    "Ì": r"\grave{I}",
    "Î": r"\hat{I}",
    "Ĩ": r"\tilde{I}",
    "J́": r"\acute{J}",
    "J̄": r"\bar{J}",
    "J̆": r"\breve{J}",
    "J̌": r"\check{J}",
    "J̈": r"\ddot{J}",
    "J̇": r"\dot{J}",
    "J̀": r"\grave{J}",
    "Ĵ": r"\hat{J}",
    "J̃": r"\tilde{J}",
    "Ḱ": r"\acute{K}",
    "K̄": r"\bar{K}",
    "K̆": r"\breve{K}",
    "Ǩ": r"\check{K}",
    "K̈": r"\ddot{K}",
    "K̇": r"\dot{K}",
    "K̀": r"\grave{K}",
    "K̂": r"\hat{K}",
    "K̃": r"\tilde{K}",
    "Ĺ": r"\acute{L}",
    "L̄": r"\bar{L}",
    "L̆": r"\breve{L}",
    "Ľ": r"\check{L}",
    "L̈": r"\ddot{L}",
    "L̇": r"\dot{L}",
    "L̀": r"\grave{L}",
    "L̂": r"\hat{L}",
    "L̃": r"\tilde{L}",
    "Ḿ": r"\acute{M}",
    "M̄": r"\bar{M}",
    "M̆": r"\breve{M}",
    "M̌": r"\check{M}",
    "M̈": r"\ddot{M}",
    "Ṁ": r"\dot{M}",
    "M̀": r"\grave{M}",
    "M̂": r"\hat{M}",
    "M̃": r"\tilde{M}",
    "Ń": r"\acute{N}",
    "N̄": r"\bar{N}",
    "N̆": r"\breve{N}",
    "Ň": r"\check{N}",
    "N̈": r"\ddot{N}",
    "Ṅ": r"\dot{N}",
    "Ǹ": r"\grave{N}",
    "N̂": r"\hat{N}",
    "Ñ": r"\tilde{N}",
    "Ó": r"\acute{O}",
    "Ō": r"\bar{O}",
    "Ŏ": r"\breve{O}",
    "Ǒ": r"\check{O}",
    "Ö": r"\ddot{O}",
    "Ȯ": r"\dot{O}",
    "Ò": r"\grave{O}",
    "Ô": r"\hat{O}",
    "Õ": r"\tilde{O}",
    "Ṕ": r"\acute{P}",
    "P̄": r"\bar{P}",
    "P̆": r"\breve{P}",
    "P̌": r"\check{P}",
    "P̈": r"\ddot{P}",
    "Ṗ": r"\dot{P}",
    "P̀": r"\grave{P}",
    "P̂": r"\hat{P}",
    "P̃": r"\tilde{P}",
    "Q́": r"\acute{Q}",
    "Q̄": r"\bar{Q}",
    "Q̆": r"\breve{Q}",
    "Q̌": r"\check{Q}",
    "Q̈": r"\ddot{Q}",
    "Q̇": r"\dot{Q}",
    "Q̀": r"\grave{Q}",
    "Q̂": r"\hat{Q}",
    "Q̃": r"\tilde{Q}",
    "Ŕ": r"\acute{R}",
    "R̄": r"\bar{R}",
    "R̆": r"\breve{R}",
    "Ř": r"\check{R}",
    "R̈": r"\ddot{R}",
    "Ṙ": r"\dot{R}",
    "R̀": r"\grave{R}",
    "R̂": r"\hat{R}",
    "R̃": r"\tilde{R}",
    "Ś": r"\acute{S}",
    "S̄": r"\bar{S}",
    "S̆": r"\breve{S}",
    "Š": r"\check{S}",
    "S̈": r"\ddot{S}",
    "Ṡ": r"\dot{S}",
    "S̀": r"\grave{S}",
    "Ŝ": r"\hat{S}",
    "S̃": r"\tilde{S}",
    "T́ ": r"\acute{T}",
    "T̄": r"\bar{T}",
    "T̆": r"\breve{T}",
    "Ť": r"\check{T}",
    "T̈": r"\ddot{T}",
    "Ṫ": r"\dot{T}",
    "T̀": r"\grave{T}",
    "T̂": r"\hat{T}",
    "T̃": r"\tilde{T}",
    "Ú": r"\acute{U}",
    "Ū": r"\bar{U}",
    "Ŭ": r"\breve{U}",
    "Ǔ": r"\check{U}",
    "Ü": r"\ddot{U}",
    "U̇": r"\dot{U}",
    "Ù": r"\grave{U}",
    "Û": r"\hat{U}",
    "Ũ": r"\tilde{U}",
    "V́": r"\acute{V}",
    "V̄": r"\bar{V}",
    "V̆": r"\breve{V}",
    "V̌": r"\check{V}",
    "V̈": r"\ddot{V}",
    "V̇": r"\dot{V}",
    "V̀": r"\grave{V}",
    "V̂": r"\hat{V}",
    "Ṽ": r"\tilde{V}",
    "Ẃ": r"\acute{W}",
    "W̄": r"\bar{W}",
    "W̆": r"\breve{W}",
    "W̌": r"\check{W}",
    "Ẅ": r"\ddot{W}",
    "Ẇ": r"\dot{W}",
    "Ẁ": r"\grave{W}",
    "Ŵ": r"\hat{W}",
    "W̃": r"\tilde{W}",
    "X́": r"\acute{X}",
    "X̄": r"\bar{X}",
    "X̆": r"\breve{X}",
    "X̌": r"\check{X}",
    "Ẍ": r"\ddot{X}",
    "Ẋ": r"\dot{X}",
    "X̀": r"\grave{X}",
    "X̂": r"\hat{X}",
    "X̃": r"\tilde{X}",
    "Ý": r"\acute{Y}",
    "Ȳ": r"\bar{Y}",
    "Y̆": r"\breve{Y}",
    "Y̌": r"\check{Y}",
    "Ÿ": r"\ddot{Y}",
    "Ẏ": r"\dot{Y}",
    "Ỳ": r"\grave{Y}",
    "Ŷ": r"\hat{Y}",
    "Ỹ": r"\tilde{Y}",
    "Ź": r"\acute{Z}",
    "Z̄": r"\bar{Z}",
    "Z̆": r"\breve{Z}",
    "Ž": r"\check{Z}",
    "Z̈": r"\ddot{Z}",
    "Ż": r"\dot{Z}",
    "Z̀": r"\grave{Z}",
    "Ẑ": r"\hat{Z}",
    "Z̃": r"\tilde{Z}",
    "Ώ": r"\acute{\Omega}",
    "Ω̄": r"\bar{\Omega}",
    "Ω̆": r"\breve{\Omega}",
    "Ω̌": r"\check{\Omega}",
    "Ω̈": r"\ddot{\Omega}",
    "Ω̇": r"\dot{\Omega}",
    "Ὼ": r"\grave{\Omega}",
    "Ω̂": r"\hat{\Omega}",
    "Ω̃": r"\tilde{\Omega}",
    "π́": r"\acute{\pi}",
    "π̄": r"\bar{\pi}",
    "π̆": r"\breve{\pi}",
    "π̌": r"\check{\pi}",
    "π̈": r"\ddot{\pi}",
    "π̇": r"\dot{\pi}",
    "π̀": r"\grave{\pi}",
    "π̂": r"\hat{\pi}",
    "π̃": r"\tilde{\pi}",
    "σ́": r"\acute{\sigma}",
    "σ̄": r"\bar{\sigma}",
    "σ̆": r"\breve{\sigma}",
    "σ̌": r"\check{\sigma}",
    "σ̈": r"\ddot{\sigma}",
    "σ̇": r"\dot{\sigma}",
    "σ̀": r"\grave{\sigma}",
    "σ̂": r"\hat{\sigma}",
    "σ̃": r"\tilde{\sigma}",
    "ί": r"\acute{\iota}",
    "ῑ": r"\bar{\iota}",
    "ῐ": r"\breve{\iota}",
    "ι̌": r"\check{\iota}",
    "ϊ": r"\ddot{\iota}",
    "ι̇": r"\dot{\iota}",
    "ὶ": r"\grave{\iota}",
    "ι̂": r"\hat{\iota}",
    "ι̃": r"\tilde{\iota}",
    "Γ́": r"\acute{\Gamma}",
    "Γ̄": r"\bar{\Gamma}",
    "Γ̆": r"\breve{\Gamma}",
    "Γ̌": r"\check{\Gamma}",
    "Γ̈": r"\ddot{\Gamma}",
    "Γ̇": r"\dot{\Gamma}",
    "Γ̀": r"\grave{\Gamma}",
    "Γ̂": r"\hat{\Gamma}",
    "Γ̃": r"\tilde{\Gamma}",
    "Π́": r"\acute{\Pi}",
    "Π̄": r"\bar{\Pi}",
    "Π̆": r"\breve{\Pi}",
    "Π̌": r"\check{\Pi}",
    "Π̈": r"\ddot{\Pi}",
    "Π̇": r"\dot{\Pi}",
    "Π̀": r"\grave{\Pi}",
    "Π̂": r"\hat{\Pi}",
    "Π̃": r"\tilde{\Pi}",
    "Ξ́": r"\acute{\Xi}",
    "Ξ̄": r"\bar{\Xi}",
    "Ξ̆": r"\breve{\Xi}",
    "Ξ̌": r"\check{\Xi}",
    "Ξ̈": r"\ddot{\Xi}",
    "Ξ̇": r"\dot{\Xi}",
    "Ξ̀": r"\grave{\Xi}",
    "Ξ̂": r"\hat{\Xi}",
    "Ξ̃": r"\tilde{\Xi}",
    "γ́": r"\acute{\gamma}",
    "γ̄": r"\bar{\gamma}",
    "γ̆": r"\breve{\gamma}",
    "γ̌": r"\check{\gamma}",
    "γ̈": r"\ddot{\gamma}",
    "γ̇": r"\dot{\gamma}",
    "γ̀": r"\grave{\gamma}",
    "γ̂": r"\hat{\gamma}",
    "γ̃": r"\tilde{\gamma}",
    "Φ́": r"\acute{\Phi}",
    "Φ̄": r"\bar{\Phi}",
    "Φ̆": r"\breve{\Phi}",
    "Φ̌": r"\check{\Phi}",
    "Φ̈": r"\ddot{\Phi}",
    "Φ̇": r"\dot{\Phi}",
    "Φ̀": r"\grave{\Phi}",
    "Φ̂": r"\hat{\Phi}",
    "Φ̃": r"\tilde{\Phi}",
    "Ψ́": r"\acute{\Psi}",
    "Ψ̄": r"\bar{\Psi}",
    "Ψ̆": r"\breve{\Psi}",
    "Ψ̌": r"\check{\Psi}",
    "Ψ̈": r"\ddot{\Psi}",
    "Ψ̇": r"\dot{\Psi}",
    "Ψ̀": r"\grave{\Psi}",
    "Ψ̂": r"\hat{\Psi}",
    "Ψ̃": r"\tilde{\Psi}",
    "ν́": r"\acute{\nu}",
    "ν̄": r"\bar{\nu}",
    "ν̆": r"\breve{\nu}",
    "ν̌": r"\check{\nu}",
    "ν̈": r"\ddot{\nu}",
    "ν̇": r"\dot{\nu}",
    "ν̀": r"\grave{\nu}",
    "ν̂": r"\hat{\nu}",
    "ν̃": r"\tilde{\nu}",
    "τ́": r"\acute{\tau}",
    "τ̄": r"\bar{\tau}",
    "τ̆": r"\breve{\tau}",
    "τ̌": r"\check{\tau}",
    "τ̈": r"\ddot{\tau}",
    "τ̇": r"\dot{\tau}",
    "τ̀": r"\grave{\tau}",
    "τ̂": r"\hat{\tau}",
    "τ̃": r"\tilde{\tau}",
    "Λ́": r"\acute{\Lambda}",
    "Λ̄": r"\bar{\Lambda}",
    "Λ̆": r"\breve{\Lambda}",
    "Λ̌": r"\check{\Lambda}",
    "Λ̈": r"\ddot{\Lambda}",
    "Λ̇": r"\dot{\Lambda}",
    "Λ̀": r"\grave{\Lambda}",
    "Λ̂": r"\hat{\Lambda}",
    "Λ̃": r"\tilde{\Lambda}",
    "ψ́": r"\acute{\psi}",
    "ψ̄": r"\bar{\psi}",
    "ψ̆": r"\breve{\psi}",
    "ψ̌": r"\check{\psi}",
    "ψ̈": r"\ddot{\psi}",
    "ψ̇": r"\dot{\psi}",
    "ψ̀": r"\grave{\psi}",
    "ψ̂": r"\hat{\psi}",
    "ψ̃": r"\tilde{\psi}",
    "χ́": r"\acute{\chi}",
    "χ̄": r"\bar{\chi}",
    "χ̆": r"\breve{\chi}",
    "χ̌": r"\check{\chi}",
    "χ̈": r"\ddot{\chi}",
    "χ̇": r"\dot{\chi}",
    "χ̀": r"\grave{\chi}",
    "χ̂": r"\hat{\chi}",
    "χ̃": r"\tilde{\chi}",
    "θ́": r"\acute{\theta}",
    "θ̄": r"\bar{\theta}",
    "θ̆": r"\breve{\theta}",
    "θ̌": r"\check{\theta}",
    "θ̈": r"\ddot{\theta}",
    "θ̇": r"\dot{\theta}",
    "θ̀": r"\grave{\theta}",
    "θ̂": r"\hat{\theta}",
    "θ̃": r"\tilde{\theta}",
    "ζ́": r"\acute{\zeta}",
    "ζ̄": r"\bar{\zeta}",
    "ζ̆": r"\breve{\zeta}",
    "ζ̌": r"\check{\zeta}",
    "ζ̇": r"\dot{\zeta}",
    "ζ̈": r"\ddot{\zeta}",
    "ζ̀": r"\grave{\zeta}",
    "ζ̂": r"\hat{\zeta}",
    "ζ̃": r"\tilde{\zeta}",
    "β́": r"\acute{\beta}",
    "β̄": r"\bar{\beta}",
    "β̆": r"\breve{\beta}",
    "β̌": r"\check{\beta}",
    "β̈": r"\ddot{\beta}",
    "β̇": r"\dot{\beta}",
    "β̀": r"\grave{\beta}",
    "β̂": r"\hat{\beta}",
    "β̃": r"\tilde{\beta}",
    "φ́": r"\acute{\phi}",
    "φ̄": r"\bar{\phi}",
    "φ̆": r"\breve{\phi}",
    "φ̌": r"\check{\phi}",
    "φ̈": r"\ddot{\phi}",
    "φ̇": r"\dot{\phi}",
    "φ̀": r"\grave{\phi}",
    "φ̂": r"\tilde{\phi}",
    "φ̃": r"\hat{\phi}",
    "μ́": r"\acute{\mu}",
    "μ̄": r"\bar{\mu}",
    "μ̆": r"\breve{\mu}",
    "μ̌": r"\check{\mu}",
    "μ̈": r"\ddot{\mu}",
    "μ̇": r"\dot{\mu}",
    "μ̀": r"\grave{\mu}",
    "μ̂": r"\hat{\mu}",
    "μ̃": r"\tilde{\mu}",
    "ώ": r"\acute{\omega}",
    "ω̄": r"\bar{\omega}",
    "ω̆": r"\breve{\omega}",
    "ω̌": r"\check{\omega}",
    "ω̈": r"\ddot{\omega}",
    "ω̇": r"\dot{\omega}",
    "ὼ": r"\grave{\omega}",
    "ω̂": r"\hat{\omega}",
    "ω̃": r"\tilde{\omega}",
    "λ́": r"\acute{\lambda}",
    "λ̄": r"\bar{\lambda}",
    "λ̆": r"\breve{\lambda}",
    "λ̌": r"\check{\lambda}",
    "λ̈": r"\ddot{\lambda}",
    "λ̇": r"\dot{\lambda}",
    "λ̀": r"\grave{\lambda}",
    "λ̂": r"\hat{\lambda}",
    "λ̃": r"\tilde{\lambda}",
    "ά": r"\acute{\alpha}",
    "ᾱ": r"\bar{\alpha}",
    "ᾰ": r"\breve{\alpha}",
    "α̌": r"\check{\alpha}",
    "α̈": r"\ddot{\alpha}",
    "α̇": r"\dot{\alpha}",
    "ὰ": r"\grave{\alpha}",
    "α̂": r"\hat{\alpha}",
    "α̃": r"\tilde{\alpha}",
    "Θ́": r"\acute{\Theta}",
    "Θ̄": r"\bar{\Theta}",
    "Θ̆": r"\breve{\Theta}",
    "Θ̌": r"\check{\Theta}",
    "Θ̈": r"\ddot{\Theta}",
    "Θ̇": r"\dot{\Theta}",
    "Θ̀": r"\grave{\Theta}",
    "Θ̂": r"\hat{\Theta}",
    "Θ̃": r"\tilde{\Theta}",
    "κ́": r"\acute{\kappa}",
    "κ̄": r"\bar{\kappa}",
    "κ̆": r"\breve{\kappa}",
    "κ̌": r"\check{\kappa}",
    "κ̈": r"\ddot{\kappa}",
    "κ̇": r"\dot{\kappa}",
    "κ̀": r"\grave{\kappa}",
    "κ̂": r"\hat{\kappa}",
    "κ̃": r"\tilde{\kappa}",
    "ḱ": r"\acute{\daleth}",
    "k̄": r"\bar{\daleth}",
    "k̆": r"\breve{\daleth}",
    "ǩ": r"\check{\daleth}",
    "k̈": r"\ddot{\daleth}",
    "k̇": r"\dot{\daleth}",
    "k̀": r"\grave{\daleth}",
    "k̂": r"\hat{\daleth}",
    "k̃": r"\tilde{\daleth}",
    "א́": r"\acute{\aleph}",
    "א̄": r"\bar{\aleph}",
    "א̆": r"\breve{\aleph}",
    "א̌": r"\check{\aleph}",
    "א̈": r"\ddot{\aleph}",
    "א̇": r"\dot{\aleph}",
    "א̀": r"\grave{\aleph}",
    "א̂": r"\hat{\aleph}",
    "א̃": r"\tilde{\aleph}",
    "í": r"\acute{\beth}",
    "ī": r"\bar{\beth}",
    "ĭ": r"\breve{\beth}",
    "ǐ": r"\check{\beth}",
    "ï": r"\ddot{\beth}",
    "i̇": r"\dot{\beth}",
    "ì": r"\grave{\beth}",
    "î": r"\hat{\beth}",
    "ĩ": r"\tilde{\beth}",
    "ή": r"\acute{\eta}",
    "η̄": r"\bar{\eta}",
    "η̆": r"\breve{\eta}",
    "η̌": r"\check{\eta}",
    "η̈": r"\ddot{\eta}",
    "η̇": r"\dot{\eta}",
    "ὴ": r"\grave{\eta}",
    "η̂": r"\hat{\eta}",
    "η̃": r"\tilde{\eta}",
    "Σ́": r"\acute{\Sigma}",
    "Σ̄": r"\bar{\Sigma}",
    "Σ̆": r"\breve{\Sigma}",
    "Σ̌": r"\check{\Sigma}",
    "Σ̈": r"\ddot{\Sigma}",
    "Σ̇": r"\dot{\Sigma}",
    "Σ̀": r"\grave{\Sigma}",
    "Σ̂": r"\hat{\Sigma}",
    "Σ̃": r"\tilde{\Sigma}",
    "ρ́": r"\acute{\rho}",
    "ρ̄": r"\bar{\rho}",
    "ρ̆": r"\breve{\rho}",
    "ρ̌": r"\check{\rho}",
    "ρ̈": r"\ddot{\rho}",
    "ρ̇": r"\dot{\rho}",
    "ρ̀": r"\grave{\rho}",
    "ρ̂": r"\hat{\rho}",
    "ρ̃": r"\tilde{\rho}",
    "ύ": r"\acute{\upsilon}",
    "ῡ": r"\bar{\upsilon}",
    "ῠ": r"\breve{\upsilon}",
    "υ̌": r"\check{\upsilon}",
    "ϋ": r"\ddot{\upsilon}",
    "υ̇": r"\dot{\upsilon}",
    "ὺ": r"\grave{\upsilon}",
    "υ̂": r"\hat{\upsilon}",
    "υ̃": r"\tilde{\upsilon}",
    # "‫"́ג‬:r"\acute{\gimel}",
    # "‫"̄ג‬:r"\bar{\gimel}",
    # "‫"̆ג‬:r"\breve{\gimel}",
    # "‫"̌ג‬:r"\check{\gimel}",
    # "‫"̈ג‬:r"\ddot{\gimel}",
    # "‫"̇ג‬:r"\dot{\gimel}",
    # "‫"̀ג‬:r"\grave{\gimel}",
    # "‫"̂ג‬:r"\hat{\gimel}",
    # "‫"̃ג‬:r"\tilde{\gimel}",
    "δ́": r"\acute{\delta}",
    "δ̄": r"\bar{\delta}",
    "δ̆": r"\breve{\delta}",
    "δ̌": r"\check{\delta}",
    "δ̈": r"\ddot{\delta}",
    "δ̇": r"\dot{\delta}",
    "δ̀": r"\grave{\delta}",
    "δ̂": r"\hat{\delta}",
    "δ̃": r"\tilde{\delta}"
}

# 
# letters = 'abcdefghijklmnopqrstuvwxyz'
# letters += letters.upper()  # tack on uppercase letters
# #letters += ''.join(greek.values())  # tack on greek letters, as a string
# accents = ('acute', 'bar', 'breve', 'check', 'ddot', 'dot', 'grave', 'hat', 'tilde', 'vec')
# for letter in letters:
#     for accent in accents:    
#         print(r' "$\ '[:-1] + accent + '{' + letter + r'}$": r"\textbackslash{}' + accent + r'\{' + letter + r'\}",\\ ')
# 
# for letter in greek.values():
#     for accent in accents:
#         print(r' "$\ '[:-1] + accent + '{' + letter + r'}$": r"\textbackslash{}' + accent + r'\{\textbackslash{}' + letter[1:] + r'\}",\\ ')

if __name__ == '__main__':
   write_text()
